# Generated by Django 5.0.1 on 2024-02-07 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 17, 26, 28, 760396, tzinfo=datetime.timezone.utc)),
        ),
    ]
