# Generated by Django 5.0.1 on 2024-02-02 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 2, 0, 0)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
