# Generated by Django 5.0.1 on 2024-02-11 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaklifeline',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='streaklifeline',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
