# Generated by Django 5.0.4 on 2024-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teammate_one',
            field=models.CharField(max_length=300),
        ),
    ]
