# Generated by Django 5.0.1 on 2024-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='total_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='previous_question',
            field=models.BooleanField(default=False),
        ),
    ]
