# Generated by Django 5.0.1 on 2024-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teammate_two',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
