# Generated by Django 5.0.1 on 2024-02-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mcq_total_responses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='correct_responces',
            new_name='correct_responses',
        ),
    ]
