# Generated by Django 5.0.1 on 2024-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_submitted_at_delete_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='selected_option',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
    ]
