# Generated by Django 5.0.1 on 2024-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
