# Generated by Django 4.2.10 on 2024-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_teammate_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teammate_two',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
