# Generated by Django 5.0.2 on 2024-02-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_streaklifeline_is_on_alter_streaklifeline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
