# Generated by Django 5.0.1 on 2024-02-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_correct_responces_mcq_correct_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correct_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
