# Generated by Django 5.0.1 on 2024-01-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('core', '0003_alter_customuser_teammate_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
