# Generated by Django 4.2.7 on 2024-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_correct_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
    ]
