# Generated by Django 5.0.1 on 2024-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct',
            field=models.CharField(choices=[('a', models.CharField(max_length=255)), ('b', models.CharField(max_length=255)), ('c', models.CharField(max_length=255)), ('d', models.CharField(max_length=255))], max_length=255),
        ),
    ]
