# Generated by Django 4.2.7 on 2024-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mcq_current_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='current_score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
    ]
