# Generated by Django 5.0.2 on 2024-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_visit',
            field=models.BooleanField(default=True),
        ),
    ]
