# Generated by Django 5.0.1 on 2024-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mcq_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Questions_to_list',
            field=models.CharField(default='NOTHING', max_length=1000),
        ),
    ]
