# Generated by Django 4.2.7 on 2024-02-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_mcq_current_score_customuser_current_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_score',
        ),
        migrations.AddField(
            model_name='submission',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
    ]
