# Generated by Django 5.0.1 on 2024-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_questions_to_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Questions_to_list',
            field=models.TextField(default='NOTHING'),
        ),
    ]
