# Generated by Django 4.2.7 on 2024-02-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_current_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='current_score',
            new_name='current_grading',
        ),
    ]
