# Generated by Django 5.0.2 on 2024-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_is_skip_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaklifeline',
            name='is_on',
        ),
        migrations.RemoveField(
            model_name='streaklifeline',
            name='questions',
        ),
        migrations.AddField(
            model_name='streaklifeline',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
