# Generated by Django 4.2.7 on 2024-02-07 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 7, 14, 6, 43, 596218)),
        ),
    ]
