# Generated by Django 4.1.3 on 2024-02-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_skipquestionlifeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='audience_poll',
            field=models.BooleanField(default=False),
        ),
    ]
