# Generated by Django 5.0.1 on 2024-02-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='audience_poll',
            field=models.BooleanField(default=False),
        ),
    ]
