# Generated by Django 5.0.3 on 2024-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_message_question_skipquestionlifeline_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiancepoll',
            name='poll',
            field=models.JSONField(default={}),
        ),
    ]
