# Generated by Django 5.0.3 on 2024-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_audiancepoll_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='negative',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='positive',
            field=models.IntegerField(default=4),
        ),
    ]
