# Generated by Django 5.0.3 on 2024-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_negative_customuser_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaklifeline',
            name='message',
            field=models.TextField(default='NULL'),
        ),
    ]
