# Generated by Django 5.0.3 on 2024-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_streaklifeline_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaklifeline',
            name='message',
        ),
    ]
