# Generated by Django 5.0.3 on 2024-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_streaklifeline_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaklifeline',
            name='conversion',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='streaklifeline',
            name='message',
            field=models.TextField(default='NULL'),
        ),
    ]
