# Generated by Django 5.0.3 on 2024-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customuser_teammate_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teammate_two',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
