# Generated by Django 4.2.10 on 2024-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_customuser_teammate_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tab_switch',
            field=models.IntegerField(default=0),
        ),
    ]
