# Generated by Django 4.2.10 on 2024-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_tab_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
