# Generated by Django 5.0.4 on 2024-04-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_mcq_question_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcq'),
        ),
        migrations.AlterField(
            model_name='skipquestionlifeline',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcq'),
        ),
        migrations.AlterField(
            model_name='streaklifeline',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcq'),
        ),
    ]
