# Generated by Django 5.0.4 on 2024-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_message_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_level',
            field=models.IntegerField(default=0),
        ),
    ]
