# Generated by Django 5.0.4 on 2024-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customuser_max_streak_customuser_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
